### ISSUE TITLE
O.volvulus CPLs

### ISSUE THREAD

**Issue by epaule** [Paul-Davis/seqcur_ticketing-system#4]
can you have a look at:

Gene : "WBGene00238522"
Gene : "WBGene00238557"
Gene : "WBGene00240125"
Gene : "WBGene00240141"
Gene : "WBGene00242649"
Gene : "WBGene00242652"
Gene : "WBGene00249634"
Gene : "WBGene00249706"

and tell Sara Lustigman of any changes?

**Comment by Paul-Davis** [comment]
migrated to jira
